# Use the official Node.js 18 image as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json ./

# Install Yarn if it's not already installed in the base image
# RUN apk add --no-cache yarn

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

RUN ls

# Build your Next.js app
RUN npm run build

# Expose the port Next.js runs on
EXPOSE 3000

# Run the app
CMD ["npm", "start"]