services:
  frontend:
    image: chatbot-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_URL: http://api:8000
        NEXT_PUBLIC_JWT_SECRET: asdflklasdjflkasjdlfjasdlfjalsdfvcxzvxqwetoyedfdzxcvmzxcvoitoadsfaxdcyxc
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - api

  api:
    image: chatbot-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
      - "11435:11434" # Added Ollama port
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      JWT_SECRET: asdflklasdjflkasjdlfjasdlfjalsdfvcxzvxqwetoyedfdzxcvmzxcvoitoadsfaxdcyxc
      JWT_ALGORITHM: HS256
      SALT: $2b$12$9vO2O/oUIee.p6zjEOCA7u
      VECTOR_DOC_DB_PATH: vector_doc_db
      COLLECTION_NAME: chat_collection
      OPENAI_API_KEY: sk-proj-BsiahkPyCrV79hWUFoqLT3BlbkFJB68DVt39wFq7ycYnkz3y
    volumes:
      - ./api:/app
      - ./api/uploaded_documents:/app/uploaded_documents
      - ./api/vector_doc_db:/app/vector_doc_db
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
