services:
  frontend:
    image: chatbot-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_JWT_SECRET: asdflklasdjflkasjdlfjasdlfjalsdfvcxzvxqwetoyedfdzxcvmzxcvoitoadsfaxdcyxc

    volumes:
      - .:/app

    restart: unless-stopped
